[context."staging".environment]
  REACT_APP_API_HOST="http://staging.reactivated.app"
  REACT_APP_GITHUB_APP_NAME="staging-reactivated-app"

[context."master".environment]
  REACT_APP_API_HOST="http://reactivated.app"
  REACT_APP_GITHUB_APP_NAME="reactivated-app"
